#!/bin/bash

docker start PHPStorm || docker run -it -d -e DISPLAY=$DISPLAY --net=host \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v $(realpath $(pwd)/../..)/Shared/volumes/home:/home/developer \
       -v $(realpath ~)/Projects:/home/developer/Projects \
       --name PHPStorm \
       phpstorm
