#!/bin/bash

docker run -ti -d --rm \
       -e DISPLAY=$DISPLAY \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v $(pwd)/volumes/home:/home/developer \
       --name qBitTorrent \
       qbittorrent
