#!/bin/bash

# ffmpeg -f x11grab -r 15 -s 1929x1080 -i :0.0+0,0 -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video2

docker run -ti -d -m=8g --rm \
       --privileged \
       -e DISPLAY=$DISPLAY \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v $(realpath $(pwd)/../..)/Shared/volumes/home:/home/developer \
       --device /dev/snd:/dev/snd \
       -v ~/.config/pulse:/home/developer/.config/pulse \
       -v /run/user/$UID/pulse/native:/run/user/$UID/pulse/native \
       -v /dev/video0:/dev/video0 \
       -v /dev/video2:/dev/video2 \
       --env PULSE_SERVER=unix:/run/user/$UID/pulse/native \
       --name obs \
       obs-studio
